# Generated by Django 5.0.1 on 2024-01-11 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbrirPromoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_tutor', models.CharField(max_length=250)),
                ('monto_a_abonar', models.FloatField()),
                ('nombre_apellido_alumno', models.CharField(max_length=250)),
                ('curso', models.CharField(max_length=50)),
                ('N_cuota', models.IntegerField()),
                ('colegio', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='CobradorNaranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_y_apellido', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TicketPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar_importe', models.FloatField(null=True)),
                ('ingresar_empresa', models.CharField(max_length=150, null=True)),
                ('ingresar_fecha', models.DateField(default='2000-01-01', null=True)),
                ('ingresar_hora', models.TimeField(default='00:00', null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('detalle_descripcion', models.TextField(null=True)),
                ('descripcion_2', models.CharField(max_length=200, null=True)),
                ('detalle_descripcion_2', models.TextField(null=True)),
                ('descripcion_3', models.CharField(max_length=200, null=True)),
                ('detalle_descripcion_3', models.TextField(null=True)),
                ('descripcion_4', models.CharField(max_length=200, null=True)),
                ('detalle_descripcion_4', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketSameep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_cliente', models.CharField(max_length=250)),
                ('cliente_suministro', models.TextField()),
                ('ingresar_factura', models.IntegerField()),
                ('ingresar_fecha', models.DateField()),
                ('ingresar_hora', models.TimeField()),
                ('paysen_ID', models.IntegerField()),
                ('importe', models.FloatField()),
                ('codigo_verificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistartPagoNaranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI_Titular', models.IntegerField()),
                ('Nombre_Titular', models.CharField(max_length=250)),
                ('importe', models.FloatField()),
                ('ingresar_fecha', models.DateField()),
                ('ingresar_hora', models.TimeField()),
                ('N_transaccion', models.FloatField()),
                ('N_operacion', models.IntegerField()),
                ('telefono_titular', models.BigIntegerField()),
                ('cobrador_naranja', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prueba.cobradornaranja')),
            ],
        ),
    ]
