# Generated by Django 4.2.7 on 2024-01-03 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingresar_importe', models.FloatField()),
                ('ingresar_empresa', models.CharField(max_length=150)),
                ('ingresar_fecha', models.DateField()),
                ('ingresar_hora', models.TimeField()),
                ('descripcion', models.CharField(max_length=200)),
                ('detalle_descripcion', models.TextField()),
                ('descripcion_2', models.CharField(max_length=200)),
                ('detalle_descripcion_2', models.TextField()),
                ('descripcion_3', models.CharField(max_length=200)),
                ('detalle_descripcion_3', models.TextField()),
                ('descripcion_4', models.CharField(max_length=200)),
                ('detalle_descripcion_4', models.TextField()),
            ],
        ),
    ]
