# Generated by Django 4.2.7 on 2024-01-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbrirPromoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_tutor', models.CharField(max_length=250)),
                ('monto_a_abonar', models.FloatField()),
                ('nombre_apellido_alumno', models.CharField(max_length=250)),
                ('curso', models.CharField(max_length=50)),
                ('N_cuota', models.IntegerField()),
                ('colegio', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='RegistartPagoNaranja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI_Titular', models.IntegerField()),
                ('Nombre_Titular', models.CharField(max_length=250)),
                ('importe', models.FloatField()),
                ('ingresar_fecha', models.DateField()),
                ('ingresar_hora', models.TimeField()),
                ('N_transaccion', models.FloatField()),
                ('N_operacion', models.IntegerField()),
                ('telefono_titular', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TicketSameep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido_cliente', models.CharField(max_length=250)),
                ('cliente_suministro', models.TextField()),
                ('ingresar_factura', models.IntegerField()),
                ('ingresar_fecha', models.DateField()),
                ('ingresar_hora', models.TimeField()),
                ('paysen_ID', models.IntegerField()),
                ('importe', models.FloatField()),
                ('codigo_verificacion', models.IntegerField()),
            ],
        ),
    ]
