# Generated by Django 5.0.1 on 2024-01-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_abrirpromoescolar_registartpagonaranja_ticketsameep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registartpagonaranja',
            name='telefono_titular',
            field=models.IntegerField(verbose_name=16),
        ),
    ]
