# Generated by Django 5.0.1 on 2024-01-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0003_alter_registartpagonaranja_telefono_titular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registartpagonaranja',
            name='telefono_titular',
            field=models.BigIntegerField(),
        ),
    ]
